### ISSUE TITLE
[Next13 starter kit with CSS modules] - Update the readme

### ISSUE THREAD

**Issue by jdwilkin4** [thisdot/starter.dev#1006]
# Background
The kit should include a thorough README with all architectural decisions the user should be aware of when utilizing it. It shouldn't rewrite docs for existing libraries but any key decisions should be documented. This is what will be visible to users on the website when they look at the details page.

# Acceptance
- [ ] Update the below template with relevant information for users who want to utilize this kit with appropriate instructions.

You should look at the Next12 and react query readme for example
https://starter.dev/kits/next12-react-query-tailwind/

**Comment by BigAB** [comment]
Something to add as well:

https://github.com/thisdot/starter.dev/pull/1181#discussion_r1136415345

**Comment by BigAB** [comment]
Also add a section about why https://github.com/thisdot/starter.dev/pull/1186 was needed
