### ISSUE TITLE
[Next13 starter kit with CSS modules] - Add Kit on the main site

### ISSUE THREAD

**Issue by jdwilkin4** [thisdot/starter.dev#1007]
# Background
The website has attempted to include all the kits appropriately but may need some added configuration to display correctly.

# Acceptance
- [ ] Ensure the kit displays on the website
- [ ] Add any missing logos for technologies as needed

**Comment by william-mimura-thisdot** [comment]
Manually closing this issue. It is merged to `next13-zustand-bulma` - will be merged to main all at once.
