### ISSUE TITLE
[BUG]: Resolve dependency conflicts for angular-ngrx-scss starter kit

### ISSUE THREAD

**Issue by jdwilkin4** [thisdot/starter.dev#1168]
It looks like there are some dependency conflicts for the angular-ngrx-scss starter kit that need to be resolved

<img width="643" alt="Screenshot 2023-03-10 at 8 24 18 AM" src="https://user-images.githubusercontent.com/67210629/224369132-371fbaec-6d48-417b-9d65-f37050640a89.png">

**Comment by honzikec** [comment]
Will be solved with #1321

**Comment by honzikec** [comment]
Resolved with https://github.com/thisdot/starter.dev/issues/1321
