### ISSUE TITLE
[starter.dev cli] Metrics handler is not being called

### ISSUE THREAD

**Issue by william-mimura-thisdot** [thisdot/starter.dev#1249]
## Issue

When running `npx @this-dot/create-starter` and following the steps to create a starter, I can't see the new metrics event being called in AWS monitors.

## Investigation

The metrics handler (serverless + AWS Lambda) is deployed as below:

- See GH Action https://github.com/thisdot/starter.dev/actions/runs/4874337784/jobs/8695135832
- See AWS Lambda https://us-east-1.console.aws.amazon.com/lambda/home?region=us-east-1#/functions/metrics-handler-production-track?tab=monitoring

I suspect this just needs an NPM deploy of our latest CLI code:
- When running the command locally `yarn start:cli` I can see the event called in AWS Lambda monitor
- Looking at https://www.npmjs.com/package/@this-dot/create-starter?activeTab=code - in `dist/index.js`, I can't find the URL for the metrics API `https://47ix8fys9k.execute-api.us-east-1.amazonaws.com/track` which is present when I build it locally

**Comment by WillHutt** [comment]
- Found out that we have not done a new deploy that has this feature
- Currently going through starter and seeing if there are any issues before deploying
  - This PR [here](https://github.com/thisdot/starter.dev/pull/1254) resolves some test issues found when doing the above

**Comment by WillHutt** [comment]
Latest version has been deployed to NPM and the tracking is working.

**Comment by dustinsgoodman** [comment]
Consideration - does the metrics work when using npm/yarn/pnpm but not when using npx or vice versa?
