### ISSUE TITLE
[pods] - Update keywords and icons for kits

### ISSUE THREAD

**Issue by jdwilkin4** [thisdot/starter.dev#1283]
The goal of this ticket is to go through all of the existing kits and create a list of updated keywords for the package.jsons and list of icons that will be show on the kit cards. 

<img width="1089" alt="Screenshot 2023-06-16 at 4 28 24 PM" src="https://github.com/thisdot/starter.dev/assets/67210629/ee99db6e-4366-42bc-9f0f-ee4900c5afcc">

It would probably be best to create a new google sheet to organize all of this data. 
When you are done, share that document with Dustin to get reviewed. 

## Acceptance criteria

- [x] Go kit by kit to create a list of updated keywords in the package.json files
- [x] Go kit by kit to determine what the complete list of icons should be
- [x] Send this list to Dustin to review for each of kit's keywords and icons

**Comment by WillHutt** [comment]
[Here](https://docs.google.com/spreadsheets/d/1wGnIaF7WSLpXQXuYwPek70jff8OCf2whuUAN7u5nF_E/edit?usp=sharing) is the Google Sheet with the updated keywords and icons for review.

Based on the current work are lost keyword count is 5 and the highest is 7. We have 10 5's, 7 6's, and 2 7's for keyword count.

**Comment by WillHutt** [comment]
Addressed feedback and am closing as it has been finished
