### ISSUE TITLE
[cra-rxjs-sc] No lockfile provided with default scaffold

### ISSUE THREAD

**Issue by dustinsgoodman** [thisdot/starter.dev#200]
# Background

See below discussion

# Acceptance
- Lock all package.json deps to version used by kit
- Remove lock file from bundle

**Comment by vyktoremario** [comment]
I think every kit should have a lock file. But we might want to add a dependabot on the project to help in updating dependencies for the kits to current versions.

**Comment by dustinsgoodman** [comment]
I think I agree but it is also forcing users to use a specific package manager when we do that. I almost think it would be better if we pinned all packages to specific versions instead and allow the developer to decide if they want to change how deps are managed. This is my 2¢

**Comment by Reshurum** [comment]
> I think I agree but it is also forcing users to use a specific package manager when we do that.

I agree with Dustin here. My understanding is for the lockfiles to even be useful in the first place, one has to run `npm ci` or whatever the `yarn` equivalent is. In our instructions we don't ask the user to install with a CI command if I recall correctly. I don't see a point in keeping them in this repository if it's complicating the rebases.

> I almost think it would be better if we pinned all packages to specific versions instead and allow the developer to decide if they want to change how deps are managed. This is my 2¢

If we are concerned with starters breaking between dependency versions, we could just pin them like you mention; however there is a downside to this that I can see. The downside to doing this is that people that use our starters would have to remember to unpin dependencies so security fixes can get installed later on.

**Comment by dustinsgoodman** [comment]
I'm pretty sure dependabot will suggest security fixes regardless of pinned versions and the same goes for other upgrade mechanisms. The pinning of versions just prevents someone from running `yarn upgrade` (or equivalent) and getting the latest versions of packages which sometimes is not intended anyway.

**Comment by Reshurum** [comment]
> 
I'm pretty sure dependabot will suggest security fixes regardless of pinned versions and the same goes for other upgrade mechanisms. The pinning of versions just prevents someone from running yarn upgrade (or equivalent) and getting the latest versions of packages which sometimes is not intended anyway.

In that case I am firmly in the "keep lockfiles out" camp. I entirely forgot about Dependabot.

**Comment by danecando** [comment]
I agree. We don't want to push any particular package manager. I think as long as we put an emphasis on keeping the core starter kits well maintained and the packages up to date we will be in good shape. The CLI tool doesn't run any particular install commands for the user, we leave that up to them so they will get a lockfile depending on whatever tool they use to install.
