### ISSUE TITLE
Workspaces appears to be setup incorrectly

### ISSUE THREAD

**Issue by dustinsgoodman** [thisdot/starter.dev#240]
There's an inconsistency in the folder name and the actual workspace name.

![Image](https://user-images.githubusercontent.com/1815379/175124827-ac5f33fb-1934-453c-b487-77df9745bb37.png)

**Comment by danecando** [comment]
Good catch. Unrelated I thought we were not including the starter kits as part of the workspace

**Comment by dustinsgoodman** [comment]
I think there was an issue with packages in the kits that used yarn without it. I could be wrong though.
