### ISSUE TITLE
Local run of `create-starter` failed to fetch correctly

### ISSUE THREAD

**Issue by dustinsgoodman** [thisdot/starter.dev#241]
![Image](https://user-images.githubusercontent.com/1815379/175125011-c0760a53-27f6-405d-a70b-8ec95976effa.png)

**Comment by dustinsgoodman** [comment]
@ihardz can you please add more details about what you were doing?

**Comment by danecando** [comment]
@dustinsgoodman @ihardz this was a bug with the url I fixed in the workspaces PR. Newer fixed version is on npm now
