### ISSUE TITLE
[website] update social share default copy

### ISSUE THREAD

**Issue by dustinsgoodman** [thisdot/starter.dev#272]
Currently, the social shares just share the link to the kit detail page. This should offer the user a default set of copy with some flavor.

# Acceptance
- Change all kit titles to "<stack> kit" (remove the word starter)
- When I click either Facebook or Twitter social share buttons, the default post should be:
> I just used the <insert kit name> by starter.dev to scaffold out my last project. It really allowed me to start building features immediately. Check out the kit: <insert link to kit>

# Notes
Example of the test for the Next kit:
> I just used the next-react-query-tailwind kit by starter.dev to scaffold out my last project. It really allowed me to start building features immediately. Check out the kit: [<insert link to kit>](https://starter.dev/kits/next-react-query-tailwind/)

**Comment by kodejuice** [comment]
After researching I've discovered It is only possible with twitter, although Facebook does not allow you to change the "What's on your mind?" text box, unless of course you're developing an application for use on Facebook.

**Comment by kodejuice** [comment]
We could append " Starter kit" to the kits meta description so one can tell what the link is about when shared on Facebook

![Image](https://user-images.githubusercontent.com/9017620/185386030-8efa635a-f604-46fc-86c3-29a3457ce7dd.png)

**Comment by kodejuice** [comment]
@dustinsgoodman

**Comment by dustinsgoodman** [comment]
We need to do a better description in general for our meta tags so that's a good shoutout. That's fine on the Facebook social bit not doing custom messages. We do need social media images and better descriptions. I'll get those into a new ticket though.
