### ISSUE TITLE
starter.dev google analytics

### ISSUE THREAD

**Issue by kahlie-huff** [thisdot/starter.dev#339]
Tag for starter.dev website:
```
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-DJRQC2FR73"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-DJRQC2FR73');
</script>
```

**Comment by morgnism** [comment]
Looks like Dane did this 6 months ago. Are we missing analytics tracking?

**Comment by morgnism** [comment]
Moving to closed. Verified the tag is working correctly.


![Image](https://user-images.githubusercontent.com/9042219/196479628-8a0d7e43-af4b-4470-b19c-ad8ee1c61c3f.png)
