### ISSUE TITLE
[solidjs-pod] 1. Add store to the project

### ISSUE THREAD

**Issue by Zelig880** [thisdot/starter.dev#363]
# Background

Each kit should have a provided state manager setup and be configured for usage.

# Acceptance

- [x] Add the chosen state management into the Kit
- [x] make sure the store works succesfully

**Comment by hdJerry** [comment]
> We see no value in using solid-query over using SolidJS' build in createSignal, createStore and createResource primitives. We'd like to stay close to Solids native ways, and will implement the kit without tanstack (edited) 

This decision was made after a long test and assessments with the guys!!

CC: @mbicknese @vyktoremario @Zelig880 @kodejuice
