### ISSUE TITLE
[solidjs-pod] 2. Add routing and create homepage

### ISSUE THREAD

**Issue by Zelig880** [thisdot/starter.dev#369]
# Background
We want to demonstrate basic routing as part of each kit. To do so, we want a homepage that directs to all the examples we've created thus far.

# Acceptance
- [x] Add and configure routing
- [x] Create a basic homepage that lives at `/`
- [x] Route the counter component to `/counter`
- [x] Route the API component to `/api-example`

# Note:
- The mock was taken from a different kit. Change the text to be align with the current kit

# Mock
![image](https://user-images.githubusercontent.com/1815379/161788828-1927cca6-f917-41f4-a971-e6bc92bb4818.png)

**Comment by hdJerry** [comment]
Paused at the moment until we add tailwind.
@Zelig880
