### ISSUE TITLE
[graphql-pod-kit1] 1. Configure API

### ISSUE THREAD

**Issue by dustinsgoodman** [thisdot/starter.dev#492]
# Background

This is for setting up Express, setting up run port, .env files, 

Regardless of REST or GraphQL, the API will have a middleware that needs configuration for things like CORS or routing for REST and schema stitching for GraphQL. This issue is to setup the API to be usable out of the box.

# Acceptance

- [ ] Can run `npm start` and and visit http://localhost:3000
- [ ] Update CORS configurations
- [ ] Ensure routing patterns are working and defined
- [ ] Setup any middleware (if applicable)

**Comment by kenslachtajr** [comment]
@jtomchak to confirm if this is done.

**Comment by jdwilkin4** [comment]
Marking this as complete based on the conversation from Slack here
https://thisdot-labs.slack.com/archives/C049D1L685C/p1669828116189789
