### ISSUE TITLE
[node-pod] 0. Generate project and establish integration point

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev#530]
# Background

To make tasks parallelizable, we should create kits via integration branches to make PRs smaller and easier to read while not breaking the upstream build. Integration branches may be cleaner and easier to implement in isolation as kits are isolated to their own directory anyway.

# Acceptance

- [ ] Generate new project in the `starters/` creating a name that includes `<framework>-<special-tech>-<store>` format
- [x] Change the name and description in the package.json
- [x] Merge change into an integration branch

**Comment by TapaiBalazs** [comment]
Created integration branch [node/starter-express](https://github.com/thisdot/starter.dev/tree/node/starter-express)
