### ISSUE TITLE
[node-pod] 1. Add store to the project

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev#532]
# Background

Each kit should have a data layer setup and configured for usage. This may be a database (prisma, edgedb, sequelize, mongoose, etc.) or a 3rd party API integration (Contentful, Sanity, etc.).

# Acceptance

- [ ] Add the chosen store into the Kit
- [ ] make sure the store works succesfully
- [ ] (if applicable) setup a docker image for the database for local development

**Comment by TapaiBalazs** [comment]
DB is going to be postresql
The API will use typeorm to connect to it

Seeding and documenting how to seed the database is not part of this story
