### ISSUE TITLE
[node-pod] 2. Setup API type definition configuration

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev#536]
# Background

## REST

This should be to setup a place to put API type definitions and ensuring out-of-the-box API type definitions are available.

## GraphQL

This should be to setup GraphQL codegen so types are auto-generated.

# Acceptance

- [ ] Add methods for generating API project types for consumption

**Comment by TapaiBalazs** [comment]
I did not find a good package that would generate typescript types for API return values.

TypeOrm Entities are the closest things to how data looks like, but those are not reusable on the front-end.
AFAIK REST is not that similar to graphQL. With graphQL we need to define a schema, that can be used to generate types, but in express REST apis we don't define schemas.

I did not find anything that would allow us to automatically generate types for us that could be used on the front-end based on the result values sent back.

cc @dustinsgoodman what do you think, how should we proceed with this?

**Comment by dustinsgoodman** [comment]
What about https://www.npmjs.com/package/openapi-typescript? Looks like if we're using OpenAPI, it can just convert those request/responses to types.
