### ISSUE TITLE
[node-pod] 3. Create healthcheck

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev#537]
# Background

All APIs should come with a default healthcheck endpoint. The healthcheck should provide a response indicating that all systems are operational. If a data source is involved, respond with data from the data source or something about that connection.

# Acceptance

- [x] There should be an endpoint or graphql query that provides a healthcheck response

**Comment by TapaiBalazs** [comment]
@ihardz 's Proposal for project structure:


1. create a controllers folder.
2. place there controllers like helloController.ts:
      ```typescript
      const router = express.Router();
      router.route('/').get(
        (req: Request, res: Response) => {
          console.log('hello form the other side');
          res.send('Hello!');
        }
      )
      export const controller: Controller = { router }
      ```

3. use it in main.ts (Generalize how to add '/api' segment to all Api Controllers routes):
app.use('/api/hello', helloController.router);
