### ISSUE TITLE
[node-pod] Set Up A CRUD Controller

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev#547]
# Notes
- Needs to use typeorm to do operations on that database table

**Comment by TapaiBalazs** [comment]
As per Dustin's request, the starter will have a very basic CRUD setup with a pre-seeded and set up database table, that will have a few entries in it with pre-population.

The goal of this task is to create REST endpoints, following best practices:

- GET /api/technology - returns all the database entries
- GET /api/technology/:id - returns the specific entry from the database
- POST /api/technology - creates a new entry and returns the newly created entry's id
- PUT /api/technology/:id - updates the entry by id
- DELETE /api/technology/:id - deletes the entry by id
