### ISSUE TITLE
[deno] 0. Generate project and establish integration point

### ISSUE THREAD

**Issue by robocel** [thisdot/starter.dev#560]
# Background

To make tasks parallelizable, we should create kits via integration branches to make PRs smaller and easier to read while not breaking the upstream build. Integration branches may be cleaner and easier to implement in isolation as kits are isolated to their own directory anyway.

# Acceptance

- [x] Generate new project in the `starters/` creating a name that includes `<framework>-<special-tech>-<store>` format
- [x] Change the name and description in the package.json
- [x] Merge change into an integration branch

**Comment by dariodjuric** [comment]
We can name the integration branch `deno/starter-oak` to be consistent with the Node integration branch, and the kit can be named `deno-oak-denodb` because we're all in on Deno.
