### ISSUE TITLE
[deno] 1. Add linting and prettier configurations

### ISSUE THREAD

**Issue by robocel** [thisdot/starter.dev#561]
# Background

Having code style consistency is important for any project. A standardized set of options should be set that can be overwritten by the implementer at a later date.

# Acceptance

- [ ] Establish eslint/tslint rules and configuration
- [ ] Install and configure prettier
- [ ] Configure editorconfig settings
- [ ] Run linting and prettier on entire project and correct any errors

# NOTE:

This task has already been completed many times on different KITs, so we should make sure to look at those configurations first and try not to reinvent the wheel :)

**Comment by robocel** [comment]
This task should include any basic or general dev tool configurations we're planning to include. So, if Deno/Fresh/Ultra/etc has any config files that can be edited that we'll likely edit, we should do that here.

**Comment by dariodjuric** [comment]
Yeah. What we could do is include the configuration file and mention in the readme how to format & lint. Thoughts?
