### ISSUE TITLE
[deno] 1. Add store to the project

### ISSUE THREAD

**Issue by robocel** [thisdot/starter.dev#562]
# Background

Each kit should have a data layer setup and configured for usage. This may be a database (prisma, edgedb, sequelize, mongoose, etc.) or a 3rd party API integration (Contentful, Sanity, etc.).

# Acceptance

- [x] Add the chosen store into the Kit
- [x] make sure the store works succesfully
- [x] (if applicable) setup a docker image for the database for local development

**Comment by robocel** [comment]
We need some form of persistence. The library type doesn't matter so much, but the node kit uses postgres. Something similar is good here. This ticket covers the installation of that tool and it's configuration and any basic code necessary to do the connection.

**Comment by dariodjuric** [comment]
[DenoDB](https://github.com/eveningkid/denodb) is a Deno-native ORM which can be used for this purpose. As for the database, we can use PostgreSQL, to be consistent with the Node starter kit.
