### ISSUE TITLE
[deno] 1. Configure API middleware

### ISSUE THREAD

**Issue by robocel** [thisdot/starter.dev#563]
# Background

Regardless of REST or GraphQL, the API will have a middleware that needs configuration for things like CORS or routing for REST and schema stitching for GraphQL. This issue is to setup the API to be usable out of the box.

# Acceptance

- [ ] Update CORS configurations
- [ ] Ensure routing patterns are working and defined
- [ ] Setup any middleware (if applicable)

**Comment by dariodjuric** [comment]
We've decided to go with GraphQL, as it is a good niche that many people might be looking for. Setting it up in Oak is simple. See ticket #145.
