### ISSUE TITLE
[qwik-pod] Add Netlify Badge To starter.dev Footer

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev#612]
We are required to have a "Deploys by Netlify" badge on the bottom footer of starter.dev

![Image](https://user-images.githubusercontent.com/1828602/206091428-7f490206-e239-488b-9bf0-705a9099946a.png)

**Comment by AllStackDev1** [comment]
How can i get this image?

**Comment by Megio** [comment]
fixed here https://github.com/thisdot/starter.dev-github-showcases/pull/1891
