### ISSUE TITLE
[deno] Add logger

### ISSUE THREAD

**Issue by dariodjuric** [thisdot/starter.dev#615]
### Acceptance Criteria

- [ ] The app should be using [Deno's logger](https://medium.com/deno-the-complete-reference/using-logger-in-deno-44c5b2372bf3) instead of console.log
- [ ] Some logging settings such as log level should be configurable through an environment variable

**Comment by tyrelchambers** [comment]
What does point #2 look like?

**Comment by dariodjuric** [comment]
For example, having an environment variable called LOG_LEVEL which can have values of DEBUG, INFO, WARNING, ERROR, and CRITICAL.
