### ISSUE TITLE
[deno] Add EditorConfig

### ISSUE THREAD

**Issue by dariodjuric** [thisdot/starter.dev#623]
As part of this ticket, we should evaluate if we can use [EditorConfig](https://editorconfig.org/) in the context of Deno project, and if so, add its configuration file.

**Comment by tyrelchambers** [comment]
This is from the official deno repo https://github.com/denoland/deno/blob/main/.editorconfig so it looks like we should be able to, though i don't exactly know what an EditorConfig would achieve. Is it a Prettier alternative?

**Comment by dariodjuric** [comment]
EditorConfig can work alongside Prettier. Editors can use it to format code as you write it, while Prettier formats the code through a manual command.

Could we try to make the EditorConfig inline with the `deno.json`'s formatting settings?
