### ISSUE TITLE
[Nuxt3-pinia-vuetify]: Add Kit to Main starter.dev site

### ISSUE THREAD

**Issue by temitopeadesoji** [thisdot/starter.dev#645]
# Background
The website has attempted to include all the kits appropriately but may need some added configuration to display correctly.

# Acceptance
- [x] Ensure the kit displays on the website
- [x] Add any missing logos for technologies as needed

**Comment by jdwilkin4** [comment]
@jesus4497 

I updated the title and description so it better matches the [template](https://github.com/thisdot/starter.dev/issues/922) created by Ken. 

Based on the acceptance criteria, the current state of the branch has met them.

<img width="599" alt="Screenshot 2023-04-28 at 11 44 33 AM" src="https://user-images.githubusercontent.com/67210629/235228400-70397d07-b0af-494f-bc54-3dd03a75ff03.png">
