### ISSUE TITLE
[qwik-graphql-tailwind] P3: No .nvmrc for node package version management

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev#668]

**Comment by SDaian** [comment]
Decided as a team we are not need an .nvmrc actually, similar like others pods doesn't have that file.

**Comment by dustinsgoodman** [comment]
@SDaian I am pushing back on other kits as well for this. I think a `.nvmrc` is a good requirement. It informs developers what version of Node is required to utilize this package. If this file is not included and the node version is not listed in the package.json, how does a developer know which version of node? This guarantees all devs use the same version.
