### ISSUE TITLE
[qwik-graphql-tailwind] P3: Make Single GraphQL Endpoint

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev#675]
- In GraphQL, you only have 1 endpoint typically. Why not just make this a useStarterQuery and always default to the [starter.dev](http://starter.dev/) backend as a demonstration

![Image](https://user-images.githubusercontent.com/1828602/208005256-fbae68df-6d2c-4bba-8847-77115dc8dc95.png)

**Comment by SDaian** [comment]
I think there is a reason why we use it as a param, also check the other pods and use the URL as a param too, so worth it change in this pod only?

**Comment by dustinsgoodman** [comment]
It's probably fine as a general-use connection but every component that would use this now has to know how to pass the URL in where in a GraphQL project, you're typically aiming to have 1 endpoint for the whole project. Hence, you have to write more code to produce the same result in many places. There are 2 ways to fix this IMO:

1. Another hook that wraps this for a specific use case
2. Just set this globally at the component level

I think both options are viable depending on the project and the decisions you want to make.
