### ISSUE TITLE
[solidjs-tailwind] address submitted feedback for drafted tweets

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev#720]
# Description
- We need to address all comments from Dustin and Allan for submitted tweets. The drafted tweets document can be found here: https://docs.google.com/document/d/1VQFLzb1tudE5MEWzXSDA3Bg7IarkqUoqvHnMBPD3XJI/edit#

**Comment by hdJerry** [comment]
All changes attended to, I await any more suggestions in case there is a need to.
@kenslachtajr

**Comment by kenslachtajr** [comment]
@hdJerry After meeting today, please confirm that all drafted tweets meet the. new criteria including images and alt text. Once these requirements have been satisfied and all feedback has been addressed and resolved, we will submit it back to Dustin for his review and approval.

**Comment by hdJerry** [comment]
I wanna confirm all drafted tweets meets the new criteria including images and alt text
@kenslachtajr

**Comment by kenslachtajr** [comment]
It looks like not all the tweets have images and alt text, but the ones needing those were originally drafted by Mark. I will have him make sure his tweets meet the updated tweet criteria.
