### ISSUE TITLE
[solidjs-tailwind] P1: fix failing test

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev#728]
# Description

- P1: fix failing test (Greeting.spec.jsx)

![Image](https://user-images.githubusercontent.com/1828602/210932822-b5c5058e-08c6-4f2a-a84e-d8527956ff90.png)

**Comment by hdJerry** [comment]
I believe we will know if this is still a problem when the ticket that fixes the API error is closed
