### ISSUE TITLE
[solidjs-tailwind] P1: lock files for pnpm aren't ignored

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev#733]
# Description
- P1: lock files for pnpm aren't ignored and need to be configured up to be ignored

**Comment by SDaian** [comment]
hey @kenslachtajr the pnpm lock files are ignored. 



![Image](https://user-images.githubusercontent.com/14813235/211798700-8e66b97c-5b43-4ee4-9836-cd1ce39617bb.png)

**Comment by AllStackDev1** [comment]
Is this on the main branch? because on my end, it is not ignored.

**Comment by SDaian** [comment]
yes, it's on Main branch, check the .gitignore:

```
starters/*/yarn.lock
starters/*/package-lock.json
starters/*/pnpm-lock.yaml
storybook-static
```
