### ISSUE TITLE
[express-apollo-prisma] 2. Setup API type definition configuration

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev#776]
# Background

## REST

This should be to setup a place to put API type definitions and ensuring out-of-the-box API type definitions are available.

## GraphQL

This should be to setup GraphQL codegen so types are auto-generated.

# Acceptance

- [ ] Add methods for generating API project types for consumption

**Comment by kenslachtajr** [comment]
This may ultimately not be needed, but we should verify when we are at this stage.

**Comment by mbicknese** [comment]
I guess Apollo does this out of the box? So the feature is implemented for free.
