### ISSUE TITLE
[express-apollo-prisma] Create kit at scale post

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev#849]
# Background

With blog posts, we always seek to drive engagement and showcase excellence.

The goal for this post is to demonstrate to people how to utilize a starter.dev kit to build a production scale application that can grow with a business. starter.dev is similar to TodoMVC in that people can quickly use the scaffolded repo to build a quick example app. Individuals new to a technology tend to struggle with understanding how an application would scale as new features are added. This is a problem you will have needed to solve with the showcase application.

This blog post should not tackle every aspect of the kit as some topics are their own blog post, e.g. managing redux at scale. Topics like module management, route management, component tree structure, shared component libraries, etc. are topics for consideration.

This post should demonstrate a better-than-just-reading-the-docs understanding of this framework and could be passed around to other developers or prospective client.

# Acceptance

- [x] Create the idea for the blog post you want to create
- [x] Get your idea approved by your pod leader
- [x] Write a blog post that accomplishes the above
- [x] Have your pod technically review your post for accuracy
- [x] Send your blog to pod lead for review
- [x] Submit to the This Dot blog Contentful for posting
- [x] Write an accompanying Tweet to promote your blog to be submitted to the marketing team

Timebox: 8 hours

**Comment by kodejuice** [comment]
[Blog Post Title]
Building a Production-Scale App with the Express-Apollo-Prisma Starter Kit

[Overview]
Learning a new technology can be overwhelming and time consuming, but what if you could quickly build a production-scale application that grows with your business needs? With the Express-Apollo-Prisma Starter Kit from starter.dev, you can quickly and easily get up and running with a modern, scalable web application.

In this blog post we will cover what's included in the kit, how to set it up and how to use the provided tools to create a scalable web application. We will also discuss how to extend the starter kit to add features like authentication. Finally, we will look at how to use the provided tools to ensure that your application is well-maintained and efficient.

By the end of this post you will have a better understanding of how to use the Express-Apollo-Prisma Starter Kit to create a production-scale web application.

**Comment by kodejuice** [comment]
@kenslachtajr @mbicknese
