### ISSUE TITLE
[solidstart-tanstack-tailwind] 1. Add store to the project

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev#857]
# Background

Each kit should have a provided state manager setup and be configured for usage.

# Acceptance

- [ ] Add the chosen state management into the Kit
- [ ] make sure the store works succesfully

**Comment by hdJerry** [comment]
SolidJs is first a state management app, so we don't need a state management library. We have createSignal and createStore. They are perfect!!

@kenslachtajr . So, we can close this ticket sir
