### ISSUE TITLE
[solidstart-tanstack-tailwind] 1. Add the styles configuration to the kit

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev#858]
# Background
Each kit should have a styling setup and be configured for usage.

# Acceptance
- [x] Add and configure the style methodology choosen for this KIT
- [x] Make sure the style work both in Dev and Production mode

**Comment by hdJerry** [comment]
The project set up comes with an option to select tailwind, so this ticket can be closed as well s we have tailwind by default.

@kenslachtajr
