### ISSUE TITLE
[serverless-apollo-contentful] Add database migration

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev#873]
# Description
- It should provide seeding and migrations as an example of how to best utilize the tooling provided to do repeatable data tasks.
- This is about moving content model changes between Contentful Environments, i.e., promoting approved model changes from staging to production. We **don't** want to migrate our local TypeScript models to Contentful.

![Image](https://user-images.githubusercontent.com/1828602/214720951-c1c0de89-a59d-4f07-9609-bbd657b1c57f.png)

**Comment by mbicknese** [comment]
I've put this ticket back to "Not Ready". Internal discussions are still ongoing on whether we want this paired with Contentful.

We already have the README instructions, guiding end-users through creating the required content model in Contentful, which might be sufficient as-is.

**Comment by mbicknese** [comment]
https://www.contentful.com/developers/docs/tutorials/cli/scripting-migrations/
