### ISSUE TITLE
[express-apollo-prisma] caching persistence

### ISSUE THREAD

**Issue by mbicknese** [thisdot/starter.dev#916]
This is a follow-up issue to #907

## Code in question

docker-compose.yml

```yml
    volumes:
      - ./redis:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
```

## Steps

 - [x] Discuss the potential options
 - [ ] Remove the mount from Docker
 - [ ] Implement changes according to decision
 
## Decision

Remove persistence from the cache (option 2).

## Considerations

 1. Mount local `redis` directory in `/var/lib/redis`
 2. Drop persistence for cache

### 1. Mount local `redis` directory in `/var/lib/redis`

By mounting a local directory inside the container, all potential files created by Redis will get stored by the host machine. On the creation of a new container (or restarting an existing one), these files will get provided from the host machine to the container.

One of these files is the back-up of all the data in Redis. We can have Redis create this file by adding `--save <time in seconds>` to the command. This prevents developers from having to populate the cache each time they create the stack.

### 2. Drop persistence for cache

Caching, by its nature, is only comprised of volatile data. It can safely be dropped without losing data or functionality from the server. Trying to restore a cache after a new start of the caching database yields little while it does introduce potential issues. (e.g., the cache might be out of sync with the actual data due to missing an invalidation request)

**Comment by mbicknese** [comment]
@iansamz , @ihardziam , @kodejuice ; looking forward to your opinions. Note that the proposed solutions might not be the only options.

**Comment by kodejuice** [comment]
I think it makes sense to drop persistence, in the serverless kit, it also wasn't included and i guess it doesn't add too much value

**Comment by mbicknese** [comment]
Let's remove the persistence from our stack. I'll put this ticket in "Ready" so it can be worked on.
