### ISSUE TITLE
[express-apollo-prisma] Add database migration

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev#927]
# Description
- It should provide seeding and migrations as an example of how to best utilize the tooling provided to do repeatable data tasks.

![Image](https://user-images.githubusercontent.com/1828602/214720951-c1c0de89-a59d-4f07-9609-bbd657b1c57f.png)

updated Acceptance Criteria:
having changes from PR: https://github.com/thisdot/starter.dev/pull/1081
* add the Seeding migration script (Docs: https://www.prisma.io/docs/guides/database/seed-database)

**Comment by iansamz** [comment]
https://www.prisma.io/docs/guides/database/seed-database
