### ISSUE TITLE
[solidstart-tanstack-tailwind] 25 Create single view repo sub header

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev#957]
# Create single repo view sub header

## Background

As a user, I can view a page for an individual repository with details about that repository. I can see the about information, tabs for code / issues / pull requests, info about how many watchers / stars / forks the repo has, and view the root folder’s contents in a file tree. At the bottom of the page I can also view the contents of the main readme page.

## Acceptance

- [ ] book icon with user name / repo name and visibility tag (public / private)
- [ ] buttons with icon, name, and count for: (buttons do not need to be functional)
    - [ ] watch
    - [ ] star
    - [ ] fork
- [ ] section will have three tab headers for different views (do not need to build the views, just the tab headers)
    - [ ] code w/ < > icon
    - [ ] issues with info icon and count of open issues
    - [ ] pull requests with icon and count of open requests

**Comment by Megio** [comment]
We already have this feature in our showcase
