### ISSUE TITLE
Review older starter kits for necessary package updates

### ISSUE THREAD

**Issue by Atrophius** [thisdot/starter.dev#962]
We have some starters that have been around for a while now which means they likely are out of date on package patch cycles. We need to review all of the older kits and identify which ones need package updates and testing. The goal of this ticket is to spawn additional tickets for each kit that needs to be updated so the work can be separated out through the team.

**Don't do major upgrades with breaking changes or changes that would change the identity of the kit, prioritize bringing minor patches up to current.**

**Comment by WillHutt** [comment]
Created tickets to address the starter kits that have out-of-date packages for minor/patch updates.

- Angular-apollo-tailwind #988 
- Angular-ngrx-scss #996 
- Deno-oak-denodb #997 
- Express-typeorm-postgres #998 
- Next12-react-query-tailwind #999 
- Nuxt2-pinia-tailwind #1000
- Qwik-graphql-tailwind #1001 
- Remix-graphql-tailwind #1002 
- Solidjs-tailwind #1003
- Svelte-kit-scss #1004 
- Vue3-apollo-quasar #1005
