### ISSUE TITLE
[Docs]: describe the CLI in detail

### ISSUE THREAD

**Issue by mbicknese** [thisdot/starter.dev#984]
### Is your feature request related to a problem? Please describe.

As a follow-up to #983, the project could do with documentation about what the CLI does and how it is used. At the moment, we have features that might not get utilised because they're not mentioned.

### Describe the solution you'd like

We need a section in the `README.md` to cover the CLI usage.

## Requirements

 - Basic introduction on the CLI usage
 - Description of each option, including its shorthand
 - (if applicable) which environment variables can be used

### Describe alternatives you've considered

Alternatively, we need to point end-users to the code so they can see what the possibilities are.

**Comment by ArslanYM** [comment]
Does this issue ask to create a section in Readme.md to highlight the CLI's used in this project OR what CLI generally is. If it is the latter , I would love to contribute to this issue?
